SELECT i.NAME, i.DATETIME
# SELECT i.ANIMAL_ID, i.DATETIME inday, o.DATETIME outday
FROM ANIMAL_INS i
LEFT OUTER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID= o.ANIMAL_ID
WHERE o.DATETIME is null
order by i.DATETIME
limit 3